apiVersion: skaffold/v2alpha2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: joshroepke/multi-client
      context: client
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        manual:
        - src: '**/*.css'
          dest: . 
        - src: '**/*.js'
          dest: . 
        - src: '**/*.html'
          dest: . 
    - image: joshroepke/multi-server
      context: server
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        manual:
        - src: '**/*.js'
          dest: . 
    - image: joshroepke/multi-worker
      context: worker
      docker: 
        dockerfile: Dockerfile.dev
      sync:
        manual:
        - src: '**/*.js'
          dest: . 
deploy: 
  kubectl:
    manifests:
      - k8s/client-deployment.yml
      - k8s/server-deployment.yml
      - k8s/worker-deployment.yml
      - k8s/server-cluster-ip-service.yml
      - k8s/client-cluster-ip-service.yml