apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: joshroeple-com-tls
spec:
  secretName: joshroepke-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: joshroepke.com
  dnsNames:
    - joshroepke.com
    - www.joshroepke.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - joshroepke.com
          - www.joshroepke.com
